---
driver_plugin: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list:
  - recipe[rs-machine_tag]
  - recipe[rs-machine_tag::monitoring]
  attributes:
    rightscale:
      instance_uuid: 01-ABCDEFG123456
    cloud:
      provider: vagrant
      public_ips:
      - null
      - ""
      - 33.33.33.10
      private_ips:
      - null
      - ""
      - 10.0.2.15
